# Generated by Django 5.2.3 on 2025-07-05 20:15

import django.db.models.deletion
import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0007_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='brand',
            field=models.CharField(choices=[('bmw', 'BMW'), ('mercedes benz', 'Mercedes Benz'), ('audi', 'Audi'), ('subaru', 'Subaru'), ('tesla', 'Tesla'), ('jaguar', 'Jaguar'), ('land rover', 'Land Rover'), ('bentley', 'Bentley'), ('bugatti', 'Bugatti'), ('ferrari', 'Ferrari'), ('lamborghini', 'Lamborghini'), ('honda', 'Honda'), ('toyota', 'Toyota'), ('chevrolet', 'Chevrolet'), ('porsche', 'Porsche')], default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='color',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='engine',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='image',
            field=models.ImageField(null=True, upload_to=main.utils.user_listing_path),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='km',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.locations'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='model',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='vin',
            field=models.CharField(default='', max_length=6),
        ),
    ]
